spring:
  application:
    name: cadastro-pessoas-spring

  datasource:
    url: jdbc:postgresql://192.168.1.17:25432/postgres
    username: postgres 
    password: postgres

  jackson:
    default-property-inclusion: non-null

springdoc:
  swagger-ui:
    path: /swagger-ui.html