spring:
  application:
    name: cadastro-pessoas-spring

  datasource:
    url: jdbc:postgresql://192.168.1.17:25432/postgres
    username: postgres 
    password: postgres

  jackson:
    default-property-inclusion: non-null

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html